source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "rails", "~> 7.0.6"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "bootsnap", require: false
gem "bunny", "~> 2.22"

group :development, :test do
  gem "standardrb", "~> 1.0", ">= 1.0.1"
  gem "dotenv-rails", "~> 2.8"
  gem "debug", platforms: %i[mri mingw x64_mingw]
end
